version: '3.8'

services:
  db:
    image: mongo
    container_name: "strong_body_db"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'pass'